version: '3.4'

services:
  apitienda:
    build:
      args:
        BUILD_CONFIGURATION: Release
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ApiTienda"
    volumes:
      - C:\Users\carlo\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\carlo\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\carlo\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\carlo\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\carlo\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - D:\APLICACIONES\Visual Studio\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - D:\APLICACIONES\Visual Studio\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages --additionalProbingPath /.nuget/fallbackpackages  \"/app/ApiTienda.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
      com.microsoft.visual-studio.project-name: "ApiTienda"
    tty: true